### ISSUE TITLE
pcaplot3d

### ISSUE THREAD

**Issue by Luuuuzi** [zarquon42b/Morpho#1]
Interpretation of the plot could be easier if the connection of line color to pc is known. For example by calling palette(rainbow(length(pcshow))); palette(); palette("default"). But there might be an easier way to include this in the documentation.

**Comment by zarquon42b** [comment]
Hi, I added option "legend" that allows to plot the legend which associates the color to each PC. Please check and close the issue if your are satisfied by the solution.

**Comment by Luuuuzi** [comment]
Perfect ! Thanks a lot !
