### ISSUE TITLE
mesh2obj lacks writeNormals option

### ISSUE THREAD

**Issue by rdinnager** [zarquon42b/Morpho#14]
Hi there,

I'm interested in saving meshes to .obj format but need to have vertex normals written into the file. Is there some reason why `mesh2obj` lacks this option while `mesh2ply` has it? It looks like like a simple modification to add it to me. I don't know your policy on contributions but I could make a pull request to add this functionality if you'd like.

**Comment by zarquon42b** [comment]
Just use vcgObjWrite mesh2obj is legacy code from the time before I had written Rvcg. 
About the Pull requests: I am open to any Pull Requests that provide reasonable improvements ;)

**Comment by rdinnager** [comment]
Ah, okay. I didn't know about that function. I should have checked `Rvcg`! Perhaps `mesh2obj` could just be updated to simply call `vcgObjWrite`? While I'm here I just wanted to say I'm enjoying using `Morpho` and `Rcvg`. Thanks for the cool and useful packages. If I think of any good improvements I will be sure to make a pull request. Cheers!

**Comment by zarquon42b** [comment]
> Perhaps mesh2obj could just be updated to simply call vcgObjWrite

This is a good idea. 
Thank you for your positive feedback!

**Comment by zarquon42b** [comment]
Done.
