### ISSUE TITLE
Error without consequence on devtools::  install

### ISSUE THREAD

**Issue by chris-english** [zarquon42b/Morpho#15]
Stephan,

Morpho devtools:: install
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS
other attached packages:
[1] Morpho_2.7

on install:
* DONE (Morpho)
Error: `call` is deprecated as of rlang 0.3.0
Called from: stop_defunct("`call` is deprecated as of rlang 0.3.0")
Browse[1]> err <<- err
Browse[1]> Q
> library(Morpho)
> str(err)
List of 4
 $ message: chr "`call` is deprecated as of rlang 0.3.0"
 $ old    : NULL
 $ new    : NULL
 $ package: NULL
 - attr(*, "class")= chr [1:4] "defunctError" "error" "condition" "condition"

We exit fine from the build and Morpho loads.

Appears to be https://github.com/r-lib/rlang/blob/master/R/cnd-signal.R line 156 ,and if I'm reading the general context correctly won't be a bigger problem till next major version, rlang 0.4.0?

Looking forward to using Morpho.

Chris

**Comment by zarquon42b** [comment]
Thanks for your info. I am using R 3.6.2 on the same OS as you and here are no issues. 
Best
Stefan
