### ISSUE TITLE
align2procSym inconsistent?

### ISSUE THREAD

**Issue by daskandalis** [zarquon42b/Morpho#20]
**Expected behaviour**: Calling align2procSym on the same data used to calculate the PCs does not return the same rotated data. `align2procSym` calls a rigid transformation to the mean shape, so I expected the same rotated data 

```
require(Morpho)
data(boneData)
set.seed(1)

proc <- procSym(boneLM)
proc_align <- align2procSym(proc,boneLM)

mean( abs(proc$orpdata[,,1] - proc_align[,,1]) )
[1] 4.115342e-05
```

The situation is much worse if parameters of `procSym` are modified.

```
proc <- procSym(boneLM, scale=FALSE)
proc_align <- align2procSym(proc,boneLM)

mean( abs(proc$orpdata[,,1] - proc_align[,,1]) )
[1] 0.5854814
```

**Comment by zarquon42b** [comment]
This is only an approximation, as in a Full Procrustes Analysis, the scaling factor is determined for all specimens at once. Aligning other data afterwards will always come with a deviation.

> The situation is much worse if parameters of procSym are modified.
You are right. The case with CSinit=T and scale=F is not handled correctly. As the scaling to CS=1 is missing. I updated the function.

**Comment by zarquon42b** [comment]
Additionally note: as procSym uses an iterative procedure to estimate the meanshape until the changes in the mean are very small, this also means that there is a cutoff point at which the iterations stop. Then the mean is calculated a last time. That means that the shapes are actually aligned to the mean of the second last iteration (it is a bit of a hen-egg problem). This seems to lead to small differences in alignment. Your second case reflects those, while the first example also contains the error from the individual vs. the sample wide scaling.

**Comment by zarquon42b** [comment]
Addendum: I also added the option "proctol" in procSym to allow for an increase of iterations to convergence. This does not address the global scaling issue but for partial proc fit. The differences are now marginal:
```
proc <- procSym(boneLM, scale=FALSE,proctol=1e-100)
proc_align <- align2procSym(proc,boneLM)

mean( abs(proc$orpdata[,,1] - proc_align[,,1]) )
[1] 1.105525e-16
```
