### ISSUE TITLE
Compatibility with Checkpoint nts format 

### ISSUE THREAD

**Issue by Ruiqi-CUB** [zarquon42b/Morpho#22]
Hi Stefan,

As the Landmark Editors is no longer maintained, I am using the Checkpoint (updated version of Landmark Editor). 

The Checkpoint no longer supported dta format when export landmarks. As I am using Morpho for the downstream analyses and it seems that it does not support nts or pts that I can export from Checkpoint. Would you mind giving me some suggestions? Is there a way to convert the nts format to dta?

Best regards
Ruiqi

**Comment by zarquon42b** [comment]
Hi @Ruiqi-CUB ,
I once created a function but you will have to test if it still works as it is quite old. It can be found here:
https://github.com/zarquon42b/RResScripts/blob/master/R/read.ckpt.r
If you want, you can maybe start from there to update/tweak it or get back to me if you do not feel proficient enough.
Best
Stefan

**Comment by Ruiqi-CUB** [comment]
Hi Stefan,
Thank you so much!
Just want to let you know, I ended up using read.pts and a csv file to input the specimen names. 

Best
Ruiqi
