### ISSUE TITLE
CRAN release 2.3.1 fails to build on clang MacOS X

### ISSUE THREAD

**Issue by jefferis** [zarquon42b/Morpho#3]
Hi Stefan,

It looks like the latest build of Rvcg fails to build with clang on the R build server:

https://cran.r-project.org/web/checks/check_results_Rvcg.html

This mainly affects macosx binaries:

https://www.r-project.org/nosvn/R.check/r-release-osx-x86_64-mavericks/Rvcg-00check.html

The error looks to me like it is related to this one

https://github.com/JoachimHahn/GAMERA/issues/12

which I guess would make it a missing include. But I see you already added an isnan patch here:

https://github.com/zarquon42b/Rvcg/commit/e22193c2c26f0b62a682ec5492573b83610a3916

So it may be that you just need to test for clang as well as gcc (as commented here https://github.com/zarquon42b/Rvcg/commit/e22193c2c26f0b62a682ec5492573b83610a3916#commitcomment-15195841).

**Comment by zarquon42b** [comment]
Hi Greg,
I fixed it here (master is already at next vcglib snapshot and c++11 only):
https://github.com/zarquon42b/Rvcg/commit/7c219ca675b949e1839c3c8c4b018693e4016243
I will release it the next days. The issue is an issue of proper
namespace injection of isnan.

Best
Stefan

**Comment by jefferis** [comment]
OK – sorry I missed that. Thanks! Best, Greg.

**Comment by zarquon42b** [comment]
Released and seemingly all OK now: https://cran.r-project.org/web/checks/check_results_Rvcg.html
