### ISSUE TITLE
Error in t.default(reprotmp$vb[1:3, ]) : argument is not a matrix

### ISSUE THREAD

**Issue by EmiDA1** [zarquon42b/Morpho#40]
Hello!

I'm having an issue with slider3d. I get the Error "Error in t.default(reprotmp$vb[1:3, ]) : argument is not a matrix". I checked both previous this [first issue](https://github.com/zarquon42b/Morpho/issues/23) and [second one](https://github.com/zarquon42b/Morpho/issues/38), but nothing seems to be working for both the solutions. I did clean the meshes with vcgClean().

> slideWithCurves <- slider3d(data, SMvector=fix, deselect=TRUE, meshlist = meshlist, surp=surp, iterations=1, mc.cores = 1, outlines=courbes)
Points will be initially projected onto surfaces 
  ------------------------------------------- 

  ------------------------------------------- 
 > Projection finished 
 ------------------------------------------- 
> Inital procrustes fit ...in...  0.00211215 secs 

> Start sliding... 
  ------------------------------------------- 
> Iteration 1 ..
> Error in t.default(reprotmp$vb[1:3, ]) : argument is not a matrix

Can you help me?

**Comment by zarquon42b** [comment]
Can you please provide a minimal example with data and code? Otherwise I have no idea what is going on.

**Comment by EmiDA1** [comment]
Hello! Thank you so much for your quick reply! I managed to find the problem on my own. I wish I'd remember how though so I could post the solution here! Everything works fine and slider3d() worked wonderfully. Thank you for your time!
