### ISSUE TITLE
Constrain rotation in icpmat, use weights

### ISSUE THREAD

**Issue by jkh1** [zarquon42b/Morpho#5]
I'm using icpmat to register sets of points. Would it be possible to constrain the rotation with a parameter similar to mindist ? Could we also pass weights to icpmat ?

**Comment by zarquon42b** [comment]
I added the options `weights` and `centerweight`, corresponding to the parameters in `computeTransform` where you can assign weights for each row of the reference configuration (https://github.com/zarquon42b/Morpho/commit/d1f38dd91ffa24233ceb76bc056a917686ea97da). Is that what you meant?
Please test.

**Comment by jkh1** [comment]
Yes. Thanks. I'll test this tomorrow.

**Comment by jkh1** [comment]
Sorry for the long delay in coming back to this. It works. Thanks a lot.

**Comment by zarquon42b** [comment]
you are welcome.
