### ISSUE TITLE
List generated instead of matrix in getTrafo4x4

### ISSUE THREAD

**Issue by J0vid** [zarquon42b/Morpho#7]
I was trying to use rotmesh.onto and running into problems- I've attached a small R project that reproduces the issue and suggests a solution. The same behavior for getTrafo4x4 is present in getTrafo.rotonto:

https://1drv.ms/f/s!AsGOC9LHYLqjje1pZzN9V6fNileg3w

**Comment by zarquon42b** [comment]
Hi @J0vid 
Your problems result from reference and Marfan.ref not being matrices - which is required by the functions. Simply convert them to matrices and everything works fine: 

```r
reference <- as.matrix(read.table("mn_ply_lm.txt"))
Marfan.ref <- as.matrix(read.table("marfanref.txt"))
```

Best
Stefan

**Comment by zarquon42b** [comment]
As I did not hear back from you, I assume this issue can be closed.
