### ISSUE TITLE
applyTransform generic should include essential args only + ...

### ISSUE THREAD

**Issue by jefferis** [zarquon42b/Morpho#9]
Re https://github.com/zarquon42b/Morpho/blob/6078f917a106f5b49805d6e53f23ef5929324edf/R/applyTransform.r#L17

I think this should really look something more like 
```r
#' @param ... additional arguments passed to methods
applyTransform <- function(x,trafo,...)UseMethod("applyTransform")

#' @rdname applyTransform
#' @export
applyTransform.matrix <- function(x,trafo,inverse=FALSE,threads=1, ...) {
```
Why? We are making calls like 

```
Morpho::applyTransform(xyzmatrix(brain), symtransformation)
```
in a package that depends on Morpho and being told that there are missing arguments (inverse and threads).

Alternatively you could perhaps put the default values in the generic. Finally it is normally considered a good idea to include `...` in the generic to allow other methods to include additional arguments.

**Comment by jefferis** [comment]
Re the last point, flexibility is the reason why most base generics look like:

```
generic <-function(x, ...)
```

**Comment by zarquon42b** [comment]
Thanks for pointing this out.
